### ISSUE TITLE
CovidData class doesn't need to be annotated as @Component

### ISSUE THREAD

**Issue by andrewlalis** [marianpmd/covid-visualizer#1]
https://github.com/marianpmd/covid-visualizer/blob/408725b625d84ac106df7fae8b08a96bb85a50b5/src/main/java/com/example/application/backend/CovidData.java#L5

Since you're only using this class for simple data storage, there's no need to mark it as a component, since this means that Spring will try to create an instance of it in case it needs to be autowired to another component that depends on it, and I don't think that's what the purpose of the CovidData class is, as far as I can tell.

**Comment by marianpmd** [comment]
Thank you , i definitely missed that one.
